### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by Eldino162** [RevTheDev/rewards#1]
Creating script environments for rewards
Error parsing script @rewards/config.lua in resource rewards: @rewards/config.lua:12: unexpected symbol near 'local'
Failed to load script config.lua.
Error loading script server/server.lua in resource rewards: @rewards/server/server.lua:114: attempt to index a nil value (global 'Config')
stack traceback:
	@rewards/server/server.lua:114: in main chunk
Failed to load script server/server.lua.

**Comment by ImRedTV** [comment]
how to correct the problem? I have it too !

**Comment by RevTheDev** [comment]
Download it again as the config was messy I have cleaned it up abit
