### ISSUE TITLE
Multiple Players Collecting reward gives Error

### ISSUE THREAD

**Issue by zetRk** [RevTheDev/rewards#2]
Hey, we are just trying out this script since we think its a very nice idea.
But we encountered an "issue"

Player1 collects Reward.
Player2 trys to collect reward and we receive an error.

Is it meant to be only 1 person being able to collect the reward in 24hrs or should more people be able to collect the reward?

SCRIPT ERROR: @rewards/server/server.lua:63: 'for' limit must be a number
> claimRewards (@rewards/server/server.lua:63)
> ref (@rewards/server/server.lua:97)
>  (@mysql-async/mysql-async.js:14898)

**Comment by RevTheDev** [comment]
I’ll get onto this please can u go into config and disable the config markers at the very bottom of the config file restart the server and do /daily let me know if the problem still exists if not I’ll have an idea of what the problem is

**Comment by zetRk** [comment]
ill give it a try right now, give me some minutes :)

**Comment by zetRk** [comment]
Alright tried your idea, but we receive the same error.

**Comment by RevTheDev** [comment]
Okay thank you I’ll look into this and get it sorted as quick as possible

**Comment by zetRk** [comment]
Alright, I found that we also dont receive the 1000 dollar which has been configured.

Config.rewards = {
    {
        type = type.money,
        value = 1000
    },
    {
        type = type.item,
        item = "lotto",
        count = 1
    },
	--[[
    {
        type = type.weapon,
        weapon = "WEAPON_PISTOL", -- if they already have the weapon, they'll only get the ammo
        ammo = 10
    }
	]]--
}

Or do we only receive this, if the random.rewards are on fault instead of true?

**Comment by RevTheDev** [comment]
Yes config.rewards is desibled while config.random_rewards_enable is true also please redownload the script as I may have fix this issue

**Comment by zetRk** [comment]
By the way. The issue only happens if random.reward is set to true.
So if we just use the normal rewards it works out fine with multiple persons claiming the reward

**Comment by RevTheDev** [comment]
Please let me know if the edit I have made fixes the issue

**Comment by zetRk** [comment]
okay, we reenabled the blips and disabled the chat command.
i tried to claim the reward but i didnt receive the reward and the reward window is not dissappearing even when i hit ESC.

**Comment by RevTheDev** [comment]
Yeah I misspelt something ahah that issue won’t happen again

**Comment by zetRk** [comment]
so i should redownload again? :D
My wife feels with you, she had the same problem (misspelling smth) and it broke the entire script she was modifying xD

**Comment by RevTheDev** [comment]
Haha ino and it can be the smallest thing that’ll take ages to find aha.

**Comment by zetRk** [comment]
ehm, i saw you changed something in the config.lua, but we kept our own config.lua for  blip coordinates and items.

I still freeze if i use the blip on the map now, and i just downloaded the script entirely new, with your config.

**Comment by RevTheDev** [comment]
Did u clear server cache

**Comment by zetRk** [comment]
wait. ill do it right away (i admit i was being dumb enough to just restart the script several times ......) you may hit me pls

**Comment by RevTheDev** [comment]
Okay please download again seems like I forgot to remove client/ from the HTML folder

**Comment by zetRk** [comment]
Well the error keeps the same way, downloaded everything, did clear cache, second person doesnt receive the reward.
if random.reward true, blips true but problem persists. Same error in console as before, same lines.

**Comment by RevTheDev** [comment]
Yeah iv narrowed it down to this line 
for i=1,chance do
This is whats causing the problem just need to figure out why so I’m having a play around with it

**Comment by RevTheDev** [comment]
Issue Fixed Please redownload the Script clear you cache

**Comment by zetRk** [comment]
alright will try tomorrow, its 1:13 am and i have to get up at7am for work. will try this after work then.

**Comment by RevTheDev** [comment]
Error is now FixThere is however another cause for this when ingame if you go into your database then into daily_free and delate anything when your ingame make sure you restart the resource or you will get this error again
