### ISSUE TITLE
Spam click on claim button give multiple rewards

### ISSUE THREAD

**Issue by parkzinc** [RevTheDev/rewards#4]
If you set a macro with 1000 clicks on the claim button you can take the reward 1000 times.

any fix for this bug ?

**Comment by parkzinc** [comment]
> If you set a macro with 1000 clicks on the claim button you can take the reward 1000 times.
> 
> any fix for this bug ?

I fixed it changin the fadeout animation in the last JS lines. (html/script.js)

function toggleshow(show) {
    if (!show) {
        $("#main").delay(1).animate({ height: 0 }, 1, "swing", function() { $("#main").hide(); });
    } else {
        $("#main").show();
        $("#main").delay(1).animate({ height: 210 }, 700);
    }
}

**Comment by mrleduck** [comment]
Yo @parkzinc could you check #5 im encountering that issue and cant seem to find the origin of it could you check it out as you have it working

**Comment by RevTheDev** [comment]
I have replaced the code with what you have suggested I have no way to test as I’m currently in the middle of rebuilding my pc
