### ISSUE TITLE
'for' limit must be a number

### ISSUE THREAD

**Issue by mrleduck** [RevTheDev/rewards#5]
Only some players are getting this error and if they spam it then its flooding the console

[      script:rewards] SCRIPT ERROR: @rewards/server/server.lua:60: 'for' limit must be a number
[      script:rewards] > claimRewards (@rewards/server/server.lua:60)
[      script:rewards] > ref (@rewards/server/server.lua:104)
[      script:rewards] > <unknown> (@mysql-async/mysql-async.js:14959)
[  script:mysql-async]

**Comment by RevTheDev** [comment]
Bug is being looked at
